### ISSUE TITLE
Could not load zlib1.dll

### ISSUE THREAD

**Issue by Lecale** [bluenote10/NimData#43]
Hi, I used nimble to install nimdata. Then I tried the most basic example suggested
```
import nimdata

echo DF.fromRange(0, 10).collect()
```
I got an error  `Could not load zlib1.dll`
Is this by any chance a common and easily fixable error?

... oh! I just found that reinstallation via choosenim made this error go away.

**Comment by bluenote10** [comment]
I tried to reproduce the problem, but for me it just works. Does the following work for you?

```
import zip/zlib
```

I guess the problem is that this `zip/zlib` package requires to have zlib library installed as a system package. On my Ubuntu system for instance, I have `/lib/x86_64-linux-gnu/libz.so.1` installed by the package `zlib1g`.

**Comment by bluenote10** [comment]
> ... oh! I just found that reinstallation via choosenim made this error go away.

oh, and I didn't read that far ;)

**Comment by ghost** [comment]
I have the same problem on windows 10 with nim 1.6.0 installed with choosenim.

```Nim
import zip/zlib
import nimdata

let df = DF.fromFile("xyz.txt")
```

compilation goes well.

output is : `could not load: zlib1.dll`

**Comment by DaneGrinder** [comment]
Me too.

choosenim 0.8.4
Nim 1.6.6

Windows 11

I'm new to Nim and haven't used Windows for 12 years so complete noob here
