### ISSUE TITLE
How to append a record (row) to a DF?

### ISSUE THREAD

**Issue by telatin** [bluenote10/NimData#62]
Sorry for the silly question here,

How to append a row to an existing dataframe?

Thanks :)

```groovy

import nimdata

let dfA = DF.fromSeq(@[
  (name: "A", age: 99)
])

let newrecord = (name: "B", age: 100)

...
```

**Comment by bluenote10** [comment]
Since the library is based on iterators, there is currently no really convenient way to do that. Basically you'd have to recollect the data and construct a new `CachedDataFrame` with the extended sequence. Something like:

```nim
let dfAExtended = DF.fromSeq(dfA.collect() & @[newrecord])
```

If your use case involves appending a lot, perhaps you could implement a custom `CachedDataFrame`.

**Comment by telatin** [comment]
No problems, this makes sense and I will simply put all my rows on a sequence till it's ready to be "dataframed"
Thanks for the quick reply
